### ISSUE TITLE
How can i set http.Agent , keepalive property

### ISSUE THREAD

**Issue by telkomops** [TooTallNate/node-https-proxy-agent#29] opened 2017-05-11 11:31 UTC
How can i set the original keepalive option to true when settings the agent to instance of http.
`var HttpsProxyAgent = require('https-proxy-agent');
this.agent = new HttpsProxyAgent("http://example.proxy.com");`
however i want to set the original option of  `http.Agent({ keepAlive: true });` is there a way to accomplish this. what is the default keepalive behavior when using the proxy

**Comment by TooTallNate** [comment] 2017-06-03 06:14
It's not implemented at the moment. I believe it's something that could be implemented in a nice generic way in the base module [`agent-base`](https://github.com/TooTallNate/node-agent-base).

Also see https://github.com/TooTallNate/node-agent-base/issues/5.

**Comment by TooTallNate** [comment] 2017-06-27 23:31
Closing since this is a duplicate of #18.

**Closed by TooTallNate** 2017-06-27 23:31 UTC
